#
# RabbitMQ Dockerfile
#

# Pull base image.
FROM rabbitmq

# Add files.
#ADD boot-rabbitmq /usr/local/bin/

# Define default command.
# CMD ["boot-rabbitmq"]

# Expose ports.
EXPOSE 5672
EXPOSE 15672
